version : "3"

services:
  ms-rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "msuser"
      RABBITMQ_DEFAULT_PASS: "msuser"
    ports:
      - "5672:5672"
    expose:
      - '5672'
  ms-mongo:
    image: mongo
    container_name: ms-mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'

  ms-mysql:
    image: mysql:5.7
    container_name: ms-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user_ms'
      MYSQL_PASSWORD: 'Ms@123'
      MYSQL_ROOT_PASSWORD: 'Ms@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ms-dbdata:/var/lib/mysql
  ms-mensageria-api:
    image: ms/ms-mensageria-api:latest
    container_name: ms-mensageria-api
    build:
      context: ../src
      dockerfile: ./MS.Mensageria.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIROMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - ms-rabbitmq
      - ms-mysql    
  ms-console:
    image: ms/console:latest
    container_name: ms-console
    build:
      context: ../src
      dockerfile: ./MS.ConsoleApp/Dockerfile
    depends_on:
      - ms-rabbitmq
      - ms-mysql
volumes:
  ms-dbdata: